spring:
  application:
    name: infobez-itmo
  datasource:
    url: jdbc:h2:mem:infobez;DB_CLOSE_DELAY=-1
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
app:
  jwt:
    issuer: infobez-itmo
    ttl: 15m
  demo:
    admin-password-hash: '$2y$12$9Qg7FRBUlJdPZbH1B5qrcu96vvltsHZTvGp7dKcFr46wBRWpbNFqC'
    user-password-hash: '$2y$12$WaLt3WVLuz9hrCHuyvtVoOmf4eehDmwtw6nKRJxVPV0AuBLGieZ6S'
